name: Michelin App CI

on:
    push:
        branches:
            - "main"
            - "develop"
            - "feat/**"
            - "fix/**"
    pull_request:
        branches: ["**"]

jobs:
    build-frontend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend
        steps:
            - name: Récupération du code
              uses: actions/checkout@v4

            - name: Configuration de Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  cache: "npm"
                  cache-dependency-path: ./frontend/package-lock.json

            - name: Installation propre des dépendances
              run: npm ci

            - name: Linting (Vérification du code)
              run: npm run lint

            - name: Tests Unitaires (Vitest)
              run: npm run test:run

            - name: Build
              run: npm run build

    build-backend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend
        steps:
            - name: Récupération du code
              uses: actions/checkout@v4

            - name: Configuration de Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  cache: "npm"
                  cache-dependency-path: ./backend/package-lock.json

            - name: Installation propre des dépendances
              run: npm ci

            - name: Build
              run: npm run build
